import type { ProviderRecord } from "../lib/normalize";

/**
 * Synthetic demonstration events. Clearly fictional — never present as live world truth.
 * Distributed across regions, categories, and severities for UI development.
 */
export function generateSyntheticEvents(now = Date.now()): ProviderRecord[] {
  const hour = 60 * 60 * 1000;
  const events: ProviderRecord[] = [
    {
      externalId: "syn-geo-001",
      headline: "[DEMO] Diplomatic talks resume after border incident",
      summary:
        "Demonstration record: two fictional states open mediated talks after a simulated border clash. No real-world event.",
      category: "geopolitical",
      severity: "high",
      confidence: "medium",
      countryCode: "XX",
      region: "Europe",
      latitude: 48.2,
      longitude: 16.37,
      occurredAt: now - 3 * hour,
      sources: [
        {
          publisher: "Demo Wire",
          sourceUrl: "https://example.com/demo/geo-001a",
          title: "Talks resume (demo)",
          verificationStatus: "corroborated",
        },
        {
          publisher: "Sample Press",
          sourceUrl: "https://example.com/demo/geo-001b",
          title: "Border incident timeline (demo)",
          verificationStatus: "unverified",
        },
        {
          publisher: "Fictional Observer",
          sourceUrl: "https://example.com/demo/geo-001c",
          title: "Mediators named (demo)",
          verificationStatus: "unverified",
        },
      ],
      whyItMatters:
        "Demo of elevated geopolitical attention when multiple sources report the same thread.",
    },
    {
      externalId: "syn-infra-002",
      headline: "[DEMO] Major port crane outage delays container traffic",
      summary:
        "Synthetic outage at a fictional Pacific port. Containers delayed 24–48 hours in the scenario.",
      category: "infrastructure",
      severity: "high",
      confidence: "high",
      countryCode: "XX",
      region: "Asia",
      latitude: 35.44,
      longitude: 139.64,
      occurredAt: now - 5 * hour,
      sources: [
        {
          publisher: "Demo Port Authority",
          sourceUrl: "https://example.com/demo/infra-002",
          title: "Crane outage notice (demo)",
          verificationStatus: "official",
        },
        {
          publisher: "Trade Sample",
          sourceUrl: "https://example.com/demo/infra-002b",
          title: "Shipping delays (demo)",
          verificationStatus: "corroborated",
        },
      ],
    },
    {
      externalId: "syn-wx-003",
      headline: "[DEMO] Category-equivalent storm approaches coastal region",
      summary:
        "Synthetic tropical system used to exercise weather severity styling and coastal map markers.",
      category: "weather",
      severity: "critical",
      confidence: "high",
      countryCode: "XX",
      region: "North America",
      latitude: 25.76,
      longitude: -80.19,
      occurredAt: now - 2 * hour,
      sources: [
        {
          publisher: "Demo Weather Service",
          sourceUrl: "https://example.com/demo/wx-003",
          title: "Storm track (demo)",
          verificationStatus: "official",
        },
        {
          publisher: "Coastal Sample News",
          sourceUrl: "https://example.com/demo/wx-003b",
          title: "Evacuation drill messaging (demo)",
          verificationStatus: "corroborated",
        },
        {
          publisher: "Marine Demo",
          sourceUrl: "https://example.com/demo/wx-003c",
          title: "Shipping advisory (demo)",
          verificationStatus: "corroborated",
        },
      ],
    },
    {
      externalId: "syn-ph-004",
      headline: "[DEMO] Cluster of respiratory illness under investigation",
      summary:
        "Public-health demonstration only. Not a real outbreak and not for clinical use.",
      category: "public_health",
      severity: "moderate",
      confidence: "low",
      countryCode: "XX",
      region: "Africa",
      latitude: -1.29,
      longitude: 36.82,
      occurredAt: now - 10 * hour,
      sources: [
        {
          publisher: "Demo Health Desk",
          sourceUrl: "https://example.com/demo/ph-004",
          title: "Cluster investigation (demo)",
          verificationStatus: "unverified",
        },
      ],
    },
    {
      externalId: "syn-cyber-005",
      headline: "[DEMO] Ransomware claim against fictional logistics network",
      summary:
        "Cybersecurity demo: attackers claim access to a made-up logistics firm. Exercise only.",
      category: "cybersecurity",
      severity: "high",
      confidence: "medium",
      countryCode: "XX",
      region: "Europe",
      latitude: 52.52,
      longitude: 13.4,
      occurredAt: now - 4 * hour,
      sources: [
        {
          publisher: "Threat Demo Lab",
          sourceUrl: "https://example.com/demo/cyber-005",
          title: "Claim analysis (demo)",
          verificationStatus: "unverified",
        },
        {
          publisher: "Industry Sample",
          sourceUrl: "https://example.com/demo/cyber-005b",
          title: "Impact assessment (demo)",
          verificationStatus: "corroborated",
        },
      ],
    },
    {
      externalId: "syn-trans-006",
      headline: "[DEMO] Transcontinental rail corridor closed after washout",
      summary:
        "Synthetic rail closure for transportation category coverage in Central Asia scenario.",
      category: "transportation",
      severity: "moderate",
      confidence: "high",
      countryCode: "XX",
      region: "Asia",
      latitude: 43.22,
      longitude: 76.85,
      occurredAt: now - 14 * hour,
      sources: [
        {
          publisher: "Rail Demo Authority",
          sourceUrl: "https://example.com/demo/trans-006",
          title: "Corridor closure (demo)",
          verificationStatus: "official",
        },
      ],
    },
    {
      externalId: "syn-energy-007",
      headline: "[DEMO] Regional grid strain after generation shortfall",
      summary:
        "Energy demo: fictional grid operator reports reserve margin stress during peak demand.",
      category: "energy",
      severity: "high",
      confidence: "high",
      countryCode: "XX",
      region: "North America",
      latitude: 32.78,
      longitude: -96.8,
      occurredAt: now - 6 * hour,
      sources: [
        {
          publisher: "Grid Demo Ops",
          sourceUrl: "https://example.com/demo/energy-007",
          title: "Reserve notice (demo)",
          verificationStatus: "official",
        },
        {
          publisher: "Energy Sample",
          sourceUrl: "https://example.com/demo/energy-007b",
          title: "Market impact (demo)",
          verificationStatus: "corroborated",
        },
      ],
    },
    {
      externalId: "syn-econ-008",
      headline: "[DEMO] Commodity exchange pauses trading on volatility tripwire",
      summary:
        "Economic demo: fictional exchange triggers a temporary halt. Not a real market event.",
      category: "economic",
      severity: "moderate",
      confidence: "medium",
      countryCode: "XX",
      region: "Asia",
      latitude: 1.35,
      longitude: 103.82,
      occurredAt: now - 8 * hour,
      sources: [
        {
          publisher: "Exchange Demo",
          sourceUrl: "https://example.com/demo/econ-008",
          title: "Trading halt (demo)",
          verificationStatus: "official",
        },
      ],
    },
    {
      externalId: "syn-geo-009",
      headline: "[DEMO] Naval exercise expands near contested strait",
      summary:
        "Geopolitical demo of multi-source reporting around a fictional maritime exercise.",
      category: "geopolitical",
      severity: "moderate",
      confidence: "medium",
      countryCode: "XX",
      region: "Asia",
      latitude: 1.25,
      longitude: 104.0,
      occurredAt: now - 20 * hour,
      sources: [
        {
          publisher: "Maritime Demo",
          sourceUrl: "https://example.com/demo/geo-009",
          title: "Exercise NOTAM (demo)",
          verificationStatus: "corroborated",
        },
        {
          publisher: "Regional Sample",
          sourceUrl: "https://example.com/demo/geo-009b",
          title: "Diplomatic reaction (demo)",
          verificationStatus: "unverified",
        },
      ],
    },
    {
      externalId: "syn-infra-010",
      headline: "[DEMO] Undersea cable fault reduces latency resilience",
      summary:
        "Infrastructure demo: synthetic cable cut between fictional landing stations.",
      category: "infrastructure",
      severity: "high",
      confidence: "medium",
      countryCode: "XX",
      region: "Oceania",
      latitude: -33.87,
      longitude: 151.21,
      occurredAt: now - 12 * hour,
      sources: [
        {
          publisher: "Cable Demo Consortium",
          sourceUrl: "https://example.com/demo/infra-010",
          title: "Fault report (demo)",
          verificationStatus: "official",
        },
        {
          publisher: "Telco Sample",
          sourceUrl: "https://example.com/demo/infra-010b",
          title: "Traffic reroute (demo)",
          verificationStatus: "corroborated",
        },
        {
          publisher: "NetOps Demo",
          sourceUrl: "https://example.com/demo/infra-010c",
          title: "Latency map (demo)",
          verificationStatus: "unverified",
        },
      ],
    },
    {
      externalId: "syn-wx-011",
      headline: "[DEMO] Extreme heat advisory for inland metro area",
      summary:
        "Weather demo for moderate severity and public-health adjacent operational awareness.",
      category: "weather",
      severity: "moderate",
      confidence: "high",
      countryCode: "XX",
      region: "Middle East",
      latitude: 24.45,
      longitude: 54.38,
      occurredAt: now - 7 * hour,
      sources: [
        {
          publisher: "Met Demo",
          sourceUrl: "https://example.com/demo/wx-011",
          title: "Heat advisory (demo)",
          verificationStatus: "official",
        },
      ],
    },
    {
      externalId: "syn-ph-012",
      headline: "[DEMO] Waterborne illness risk after flooding",
      summary:
        "Public-health scenario only. Synthetic flood aftermath — not real case counts.",
      category: "public_health",
      severity: "high",
      confidence: "medium",
      countryCode: "XX",
      region: "South America",
      latitude: -3.12,
      longitude: -60.02,
      occurredAt: now - 18 * hour,
      sources: [
        {
          publisher: "Hydro Demo Desk",
          sourceUrl: "https://example.com/demo/ph-012",
          title: "Water quality alert (demo)",
          verificationStatus: "corroborated",
        },
        {
          publisher: "Clinic Sample Network",
          sourceUrl: "https://example.com/demo/ph-012b",
          title: "Surveillance note (demo)",
          verificationStatus: "unverified",
        },
      ],
    },
    {
      externalId: "syn-cyber-013",
      headline: "[DEMO] Credential stuffing wave targets fictional hospital portals",
      summary:
        "Cybersecurity demo. No real facilities involved. Illustrates healthcare-adjacent infrastructure risk without PHI.",
      category: "cybersecurity",
      severity: "critical",
      confidence: "medium",
      countryCode: "XX",
      region: "North America",
      latitude: 41.88,
      longitude: -87.63,
      occurredAt: now - 1.5 * hour,
      sources: [
        {
          publisher: "ISAC Demo",
          sourceUrl: "https://example.com/demo/cyber-013",
          title: "Credential stuffing advisory (demo)",
          verificationStatus: "corroborated",
        },
        {
          publisher: "Security Sample",
          sourceUrl: "https://example.com/demo/cyber-013b",
          title: "IOC summary (demo)",
          verificationStatus: "unverified",
        },
        {
          publisher: "Ops Demo Blog",
          sourceUrl: "https://example.com/demo/cyber-013c",
          title: "Mitigations (demo)",
          verificationStatus: "unverified",
        },
      ],
    },
    {
      externalId: "syn-trans-014",
      headline: "[DEMO] Airspace restriction for volcanic ash plume",
      summary:
        "Transportation demo around a fictional volcanic plume and NOTAM-style restriction.",
      category: "transportation",
      severity: "high",
      confidence: "high",
      countryCode: "XX",
      region: "Oceania",
      latitude: -8.11,
      longitude: 112.92,
      occurredAt: now - 9 * hour,
      sources: [
        {
          publisher: "Aviation Demo Authority",
          sourceUrl: "https://example.com/demo/trans-014",
          title: "Ash NOTAM (demo)",
          verificationStatus: "official",
        },
        {
          publisher: "Airline Sample",
          sourceUrl: "https://example.com/demo/trans-014b",
          title: "Reroutes (demo)",
          verificationStatus: "corroborated",
        },
      ],
    },
    {
      externalId: "syn-energy-015",
      headline: "[DEMO] LNG terminal maintenance extended unexpectedly",
      summary:
        "Energy demo: extended outage at a fictional LNG terminal affecting regional supply planning.",
      category: "energy",
      severity: "moderate",
      confidence: "high",
      countryCode: "XX",
      region: "Europe",
      latitude: 53.55,
      longitude: 9.99,
      occurredAt: now - 30 * hour,
      sources: [
        {
          publisher: "Terminal Demo Ops",
          sourceUrl: "https://example.com/demo/energy-015",
          title: "Maintenance update (demo)",
          verificationStatus: "official",
        },
      ],
    },
    {
      externalId: "syn-econ-016",
      headline: "[DEMO] Central bank emergency liquidity facility activated",
      summary:
        "Economic demo of a fictional liquidity facility — not a real monetary policy action.",
      category: "economic",
      severity: "high",
      confidence: "high",
      countryCode: "XX",
      region: "Europe",
      latitude: 50.11,
      longitude: 8.68,
      occurredAt: now - 11 * hour,
      sources: [
        {
          publisher: "Central Demo Bank",
          sourceUrl: "https://example.com/demo/econ-016",
          title: "Facility notice (demo)",
          verificationStatus: "official",
        },
        {
          publisher: "Markets Sample",
          sourceUrl: "https://example.com/demo/econ-016b",
          title: "Market reaction (demo)",
          verificationStatus: "corroborated",
        },
      ],
    },
    {
      externalId: "syn-geo-017",
      headline: "[DEMO] Ceasefire monitors report checkpoint delay",
      summary:
        "Geopolitical informational demo for lower-severity feed density testing.",
      category: "geopolitical",
      severity: "informational",
      confidence: "low",
      countryCode: "XX",
      region: "Middle East",
      latitude: 33.89,
      longitude: 35.5,
      occurredAt: now - 16 * hour,
      sources: [
        {
          publisher: "Monitor Demo Mission",
          sourceUrl: "https://example.com/demo/geo-017",
          title: "Checkpoint note (demo)",
          verificationStatus: "unverified",
        },
      ],
    },
    {
      externalId: "syn-infra-018",
      headline: "[DEMO] Desalination plant offline after pump failure",
      summary:
        "Infrastructure demo for Middle East water systems operational awareness scenarios.",
      category: "infrastructure",
      severity: "moderate",
      confidence: "high",
      countryCode: "XX",
      region: "Middle East",
      latitude: 25.2,
      longitude: 55.27,
      occurredAt: now - 22 * hour,
      sources: [
        {
          publisher: "Utility Demo",
          sourceUrl: "https://example.com/demo/infra-018",
          title: "Plant status (demo)",
          verificationStatus: "official",
        },
      ],
    },
    {
      externalId: "syn-wx-019",
      headline: "[DEMO] Wildfire smoke degrades air quality across corridor",
      summary:
        "Weather demo spanning multi-region smoke plume for map clustering tests.",
      category: "weather",
      severity: "high",
      confidence: "high",
      countryCode: "XX",
      region: "North America",
      latitude: 49.28,
      longitude: -123.12,
      occurredAt: now - 15 * hour,
      sources: [
        {
          publisher: "Air Quality Demo",
          sourceUrl: "https://example.com/demo/wx-019",
          title: "AQI spike (demo)",
          verificationStatus: "official",
        },
        {
          publisher: "Fire Sample Desk",
          sourceUrl: "https://example.com/demo/wx-019b",
          title: "Fire perimeter (demo)",
          verificationStatus: "corroborated",
        },
      ],
    },
    {
      externalId: "syn-ph-020",
      headline: "[DEMO] Vector control campaign expanded in coastal districts",
      summary:
        "Public-health demo of a synthetic vector-control expansion — no real patient data.",
      category: "public_health",
      severity: "informational",
      confidence: "medium",
      countryCode: "XX",
      region: "Africa",
      latitude: 6.52,
      longitude: 3.38,
      occurredAt: now - 40 * hour,
      sources: [
        {
          publisher: "Vector Demo Unit",
          sourceUrl: "https://example.com/demo/ph-020",
          title: "Campaign update (demo)",
          verificationStatus: "official",
        },
      ],
    },
    {
      externalId: "syn-cyber-021",
      headline: "[DEMO] DNS hijack attempt blocked at regional ISP",
      summary:
        "Cybersecurity informational demo of a blocked attack path. Synthetic only.",
      category: "cybersecurity",
      severity: "moderate",
      confidence: "high",
      countryCode: "XX",
      region: "South America",
      latitude: -23.55,
      longitude: -46.63,
      occurredAt: now - 26 * hour,
      sources: [
        {
          publisher: "ISP Demo SOC",
          sourceUrl: "https://example.com/demo/cyber-021",
          title: "DNS attempt blocked (demo)",
          verificationStatus: "official",
        },
      ],
    },
    {
      externalId: "syn-trans-022",
      headline: "[DEMO] Key canal transit backlog exceeds 48 hours",
      summary:
        "Transportation demo of a fictional canal backlog for logistics risk scoring.",
      category: "transportation",
      severity: "high",
      confidence: "high",
      countryCode: "XX",
      region: "Global",
      latitude: 9.08,
      longitude: -79.68,
      occurredAt: now - 13 * hour,
      sources: [
        {
          publisher: "Canal Demo Authority",
          sourceUrl: "https://example.com/demo/trans-022",
          title: "Transit backlog (demo)",
          verificationStatus: "official",
        },
        {
          publisher: "Shipping Sample",
          sourceUrl: "https://example.com/demo/trans-022b",
          title: "Queue length (demo)",
          verificationStatus: "corroborated",
        },
      ],
    },
    {
      externalId: "syn-energy-023",
      headline: "[DEMO] Offshore wind farm curtailed after cable anomaly",
      summary:
        "Energy demo: synthetic curtailment after an instrumentation anomaly.",
      category: "energy",
      severity: "informational",
      confidence: "medium",
      countryCode: "XX",
      region: "Europe",
      latitude: 54.9,
      longitude: 7.5,
      occurredAt: now - 35 * hour,
      sources: [
        {
          publisher: "Wind Demo Ops",
          sourceUrl: "https://example.com/demo/energy-023",
          title: "Curtailment notice (demo)",
          verificationStatus: "official",
        },
      ],
    },
    {
      externalId: "syn-econ-024",
      headline: "[DEMO] Export license freeze for dual-use components",
      summary:
        "Economic/geopolitical-adjacent demo of a fictional export control action.",
      category: "economic",
      severity: "moderate",
      confidence: "medium",
      countryCode: "XX",
      region: "North America",
      latitude: 38.9,
      longitude: -77.04,
      occurredAt: now - 28 * hour,
      sources: [
        {
          publisher: "Trade Demo Office",
          sourceUrl: "https://example.com/demo/econ-024",
          title: "License freeze (demo)",
          verificationStatus: "official",
        },
        {
          publisher: "Industry Sample",
          sourceUrl: "https://example.com/demo/econ-024b",
          title: "Sector impact (demo)",
          verificationStatus: "unverified",
        },
      ],
    },
    {
      externalId: "syn-geo-025",
      headline: "[DEMO] Sanctions list expanded for shell company network",
      summary:
        "Geopolitical demo of a fictional sanctions update for multi-source feed testing.",
      category: "geopolitical",
      severity: "high",
      confidence: "high",
      countryCode: "XX",
      region: "Global",
      latitude: 40.71,
      longitude: -74.01,
      occurredAt: now - 4.5 * hour,
      sources: [
        {
          publisher: "Sanctions Demo Registry",
          sourceUrl: "https://example.com/demo/geo-025",
          title: "List expansion (demo)",
          verificationStatus: "official",
        },
        {
          publisher: "Compliance Sample",
          sourceUrl: "https://example.com/demo/geo-025b",
          title: "Screening guidance (demo)",
          verificationStatus: "corroborated",
        },
        {
          publisher: "Legal Demo Brief",
          sourceUrl: "https://example.com/demo/geo-025c",
          title: "Scope analysis (demo)",
          verificationStatus: "unverified",
        },
      ],
    },
    {
      externalId: "syn-infra-026",
      headline: "[DEMO] Hospital generator failover test fails acceptance",
      summary:
        "Infrastructure demo only — no real hospital named. Exercises critical severity without clinical data.",
      category: "infrastructure",
      severity: "critical",
      confidence: "high",
      countryCode: "XX",
      region: "Africa",
      latitude: -26.2,
      longitude: 28.04,
      occurredAt: now - 0.8 * hour,
      sources: [
        {
          publisher: "Facilities Demo Audit",
          sourceUrl: "https://example.com/demo/infra-026",
          title: "Failover test result (demo)",
          verificationStatus: "official",
        },
        {
          publisher: "Health Ops Sample",
          sourceUrl: "https://example.com/demo/infra-026b",
          title: "Continuity note (demo)",
          verificationStatus: "corroborated",
        },
      ],
    },
    {
      externalId: "syn-wx-027",
      headline: "[DEMO] River flood stage exceeds major threshold",
      summary:
        "Weather demo of a major flood stage on a fictional river basin.",
      category: "weather",
      severity: "critical",
      confidence: "high",
      countryCode: "XX",
      region: "South America",
      latitude: -34.6,
      longitude: -58.38,
      occurredAt: now - 2.2 * hour,
      sources: [
        {
          publisher: "Hydrology Demo",
          sourceUrl: "https://example.com/demo/wx-027",
          title: "Flood stage (demo)",
          verificationStatus: "official",
        },
        {
          publisher: "Civil Demo Agency",
          sourceUrl: "https://example.com/demo/wx-027b",
          title: "Shelter activation (demo)",
          verificationStatus: "corroborated",
        },
        {
          publisher: "Local Sample",
          sourceUrl: "https://example.com/demo/wx-027c",
          title: "Road closures (demo)",
          verificationStatus: "unverified",
        },
      ],
    },
    {
      externalId: "syn-ph-028",
      headline: "[DEMO] Cold-chain excursion reported for vaccine shipment",
      summary:
        "Public-health logistics demo. Synthetic shipment only — no lot numbers or patient data.",
      category: "public_health",
      severity: "moderate",
      confidence: "medium",
      countryCode: "XX",
      region: "Oceania",
      latitude: -36.85,
      longitude: 174.76,
      occurredAt: now - 19 * hour,
      sources: [
        {
          publisher: "Cold Chain Demo",
          sourceUrl: "https://example.com/demo/ph-028",
          title: "Excursion report (demo)",
          verificationStatus: "official",
        },
      ],
    },
    {
      externalId: "syn-cyber-029",
      headline: "[DEMO] Industrial control anomaly on fictional water utility",
      summary:
        "Cyber-physical demo for OT-style situational awareness. Synthetic utility only.",
      category: "cybersecurity",
      severity: "high",
      confidence: "low",
      countryCode: "XX",
      region: "Europe",
      latitude: 59.33,
      longitude: 18.07,
      occurredAt: now - 6.5 * hour,
      sources: [
        {
          publisher: "OT Demo Center",
          sourceUrl: "https://example.com/demo/cyber-029",
          title: "Anomaly bulletin (demo)",
          verificationStatus: "unverified",
        },
        {
          publisher: "Utility Sample",
          sourceUrl: "https://example.com/demo/cyber-029b",
          title: "Operational status (demo)",
          verificationStatus: "corroborated",
        },
      ],
    },
    {
      externalId: "syn-trans-030",
      headline: "[DEMO] Major airport ground-stop for staffing shortfall",
      summary:
        "Transportation demo of a temporary ground-stop at a fictional hub airport.",
      category: "transportation",
      severity: "moderate",
      confidence: "high",
      countryCode: "XX",
      region: "Europe",
      latitude: 51.47,
      longitude: -0.46,
      occurredAt: now - 5.5 * hour,
      sources: [
        {
          publisher: "Airport Demo Ops",
          sourceUrl: "https://example.com/demo/trans-030",
          title: "Ground-stop (demo)",
          verificationStatus: "official",
        },
      ],
    },
    {
      externalId: "syn-energy-031",
      headline: "[DEMO] Pipeline pressure anomaly triggers isolation valves",
      summary:
        "Energy infrastructure demo of a pipeline isolation event — fictional corridor.",
      category: "energy",
      severity: "critical",
      confidence: "medium",
      countryCode: "XX",
      region: "North America",
      latitude: 29.76,
      longitude: -95.37,
      occurredAt: now - 3.5 * hour,
      sources: [
        {
          publisher: "Pipeline Demo Control",
          sourceUrl: "https://example.com/demo/energy-031",
          title: "Isolation notice (demo)",
          verificationStatus: "official",
        },
        {
          publisher: "Safety Sample",
          sourceUrl: "https://example.com/demo/energy-031b",
          title: "Community advisory (demo)",
          verificationStatus: "corroborated",
        },
      ],
    },
    {
      externalId: "syn-econ-032",
      headline: "[DEMO] Sovereign debt auction undersubscribed",
      summary:
        "Economic demo of weak demand at a fictional sovereign auction.",
      category: "economic",
      severity: "informational",
      confidence: "high",
      countryCode: "XX",
      region: "Africa",
      latitude: -15.79,
      longitude: -47.88,
      occurredAt: now - 45 * hour,
      sources: [
        {
          publisher: "Debt Demo Office",
          sourceUrl: "https://example.com/demo/econ-032",
          title: "Auction result (demo)",
          verificationStatus: "official",
        },
      ],
    },
    {
      externalId: "syn-geo-033",
      headline: "[DEMO] Election observation mission reports procedural delay",
      summary:
        "Geopolitical informational demo for lower-priority feed items.",
      category: "geopolitical",
      severity: "informational",
      confidence: "medium",
      countryCode: "XX",
      region: "Africa",
      latitude: 9.03,
      longitude: 38.74,
      occurredAt: now - 50 * hour,
      sources: [
        {
          publisher: "Observation Demo Mission",
          sourceUrl: "https://example.com/demo/geo-033",
          title: "Procedural delay (demo)",
          verificationStatus: "corroborated",
        },
      ],
    },
    {
      externalId: "syn-infra-034",
      headline: "[DEMO] Data center cooling failure causes regional cloud degradation",
      summary:
        "Infrastructure demo of a synthetic cloud region degradation after cooling failure.",
      category: "infrastructure",
      severity: "high",
      confidence: "high",
      countryCode: "XX",
      region: "Asia",
      latitude: 37.57,
      longitude: 126.98,
      occurredAt: now - 7.5 * hour,
      sources: [
        {
          publisher: "Cloud Demo Status",
          sourceUrl: "https://example.com/demo/infra-034",
          title: "Region degradation (demo)",
          verificationStatus: "official",
        },
        {
          publisher: "SRE Sample",
          sourceUrl: "https://example.com/demo/infra-034b",
          title: "Customer impact (demo)",
          verificationStatus: "corroborated",
        },
      ],
    },
    {
      externalId: "syn-wx-035",
      headline: "[DEMO] Blizzard closes mountain passes",
      summary:
        "Weather transportation-adjacent demo for multi-category filter testing.",
      category: "weather",
      severity: "moderate",
      confidence: "high",
      countryCode: "XX",
      region: "Europe",
      latitude: 46.82,
      longitude: 9.83,
      occurredAt: now - 17 * hour,
      sources: [
        {
          publisher: "Alpine Demo Met",
          sourceUrl: "https://example.com/demo/wx-035",
          title: "Pass closures (demo)",
          verificationStatus: "official",
        },
      ],
    },
  ];

  return events.map((e) => ({
    ...e,
    isSynthetic: true,
    generatedContentDisclosure:
      "DEMO DATA: System-generated synthetic summary for prototype demonstration. Not a real-world event or verified fact.",
  }));
}
